# CI/PR Pipeline that deploys an TF template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/tf-templates/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/tf-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg


stages:
  - stage: Plan
    jobs:
      - job: Install Terraform and plan deployment
        steps:
          - script: | 
              wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
              unzip terraform_${tf_version}_linux_amd64.zip
              echo $PATH
              mv terraform /usr/local/bin
              rm terraform_${tf_version}_linux_amd64.zip
            displayName: Install Terraform
            env:
              tf_version: 0.12.28
            
             