# CI/PR Pipeline that deploys an TF template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/tf-templates/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/tf-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg


stages:
  - stage: Plan
    jobs:
      - job: Plan_deployment
        steps:
          - script: | 
              wget -q https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
              unzip terraform_${tf_version}_linux_amd64.zip
              echo $PATH
              pwd && ls -l 
              mkdir bin && mv terraform bin/ && export PATH="$PATH:$(pwd)/bin" && echo $PATH
              rm terraform_${tf_version}_linux_amd64.zip
              terraform version
            displayName: Install Terraform
            env:
              tf_version: 0.12.28
            
          
